name: Resolve Docker Tags

on:
  workflow_dispatch:

jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo jq curl

      - name: Generate resolved_images.txt
        run: |
          > resolved_images.txt
          while IFS= read -r line || [ -n "$line" ]; do
              [[ -z "$line" ]] && continue
              [[ "$line" =~ ^\s*# ]] && continue

              image=$(echo "$line" | awk '{print $NF}')
              tag="latest"
              if [[ "$image" == *:* ]]; then
                  tag="${image##*:}"
              fi

              repo=$(echo "$image" | cut -d ':' -f1)
              if [ "$tag" != "latest" ]; then
                  echo "$image" >> resolved_images.txt
                  continue
              fi

              echo "解析 latest：$repo"
              digest=$(skopeo inspect docker://$repo:latest | jq -r '.Digest')

              namespace=$(echo $repo | cut -d '/' -f1)
              reponame=$(echo $repo | cut -d '/' -f2)

              tags=$(curl -s "https://hub.docker.com/v2/repositories/$namespace/$reponame/tags?page_size=100" | jq -r '.results[].name')

              for t in $tags; do
                  tag_digest=$(skopeo inspect docker://$repo:$t 2>/dev/null | jq -r '.Digest' || true)
                  if [[ "$tag_digest" == "$digest" ]]; then
                      echo "$repo:$t" >> resolved_images.txt
                      echo "✔️  latest 对应 tag: $t"
                      break
                  fi
              done

          done < images.txt

      - name: Upload resolved file
        uses: actions/upload-artifact@v4
        with:
          name: resolved_images
          path: resolved_images.txt
